version: "3"
services:
  agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: capuchin
    environment:
      - ACAPY_LABEL=CAPUCHIN
      - ACAPY_ENDPOINT=http://capuchin:8899
      - ACAPY_OUTBOUND_TRANSPORT=http
      - ACAPY_ADMIN=[0.0.0.0, 8050]
      - ACAPY_WALLET_TYPE=indy
      - ACAPY_WALLET_NAME=capuchin.wallet
      - ACAPY_WALLET_SEED=capuchin000000000000000000000000 #from registered DID on von-network
      - ACAPY_WALLET_KEY=5muChGJGRucvQS82vTScaHByUFQvNubeqK2L2A7QvpPw #from registered DID on von-network
      - ACAPY_GENESIS_URL=http://von_webserver_1:8000/genesis
      - ACAPY_AGENT_LABEL=CAPUCHIN.AGENT
      - ACAPY_WEBHOOK_URL=http://main1:5000/webhooks 
      - ACAPY_TRACE_TARGET=log
      - ACAPT_TRACE_TAG=acapy.events
      - ACAPY_TRACE_LABEL=capuchin.agent.trace
    ports:
      - 8050:8050
      - 8899:8899
 
    entrypoint: aca-py
    #running agent as wallet (capuchin)
    #inbound transport is localhost and should not be used by anyone
    command: start --inbound-transport http capuchin 8899 --auto-ping-connection --auto-respond-messages --preserve-exchange-records --auto-provision --emit-new-didcomm-prefix --replace-public-did --admin-insecure-mode --replace-public-did --recreate-wallet
networks:
  default:
    external: true
    name: von_von

    
