version: '3'
# init main app image
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: genting:latest
    container_name: genting_controller
    ports:
      - "5001:5000"
networks:
  default:
    external: true
    name: von_von